# Generated by Django 2.0.3 on 2018-03-27 06:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops_nearby', '0002_user_preferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maplocation',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326, verbose_name='longitude/latitude'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_pic',
            field=models.ImageField(default='http://placehold.it/150x150', null=True, upload_to='pic_folder/'),
        ),
    ]
