# Generated by Django 2.0.3 on 2018-04-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops_nearby', '0004_auto_20180403_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dislike_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
