# Generated by Django 2.0.3 on 2018-04-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops_nearby', '0005_user_dislike_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dislike_time',
        ),
    ]
