# Generated by Django 2.0.3 on 2018-04-05 05:13

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shops_nearby', '0006_remove_user_dislike_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geolocalisation',
            field=django_google_maps.fields.GeoLocationField(default='Rabat', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
    ]
