# Generated by Django 2.0.3 on 2018-04-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops_nearby', '0011_auto_20180405_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='geolocalisation',
        ),
    ]
